version: "3"

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    environment:
      VIRTUAL_PORT: 80
      VIRTUAL_HOST: monitoremulator.com
      LETSENCRYPT_HOST: monitoremulator.com
      LETSENCRYPT_EMAIL: tajantonius@gmail.com

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    environment:
      DB_URL: mongodb://db/monemu
      VIRTUAL_PORT: 8080
      VIRTUAL_HOST: api.monitoremulator.com
      LETSENCRYPT_HOST: api.monitoremulator.com
      LETSENCRYPT_EMAIL: tajantonius@gmail.com
      
  db:
    image: mongo:4.0-xenial
    volumes:
      - monemu:/data/db

volumes:
  monemu:

networks:
  default:
    external:
      name: letsencrypt

