version: '3'

services: 
  web:
    build: ./web
    ports:
      - 80:80
    volumes:
      - ./web:/web
    command: ./docker-entrypoint.sh

  api:
    build: ./api
    ports: 
      - 8080:8080
    environment: 
      DB_URL: mongodb://db/monemu
    volumes:
      - ./api:/api
    command: ./docker-entrypoint.sh

  db:
    image: mongo:4.0-xenial
    ports: 
      - 27017:27017
    volumes:
      - monemu:/data/db

volumes:
  monemu: